name: cd-oauth-server

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch to build'
        required: true
        default: 'master'

  push:
    paths:
      - 'oauth-server/**'

  pull_request:
    types: [opened, reopened, edited, synchronize, closed]
    paths:
      - 'oauth-server/**'

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: oauth-server/src/API
      IMAGE_FILE: oauth-server/src/API/Dockerfile
      IMAGE_NAME: oauth-server
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      BRANCH: ${{ github.event.inputs.branch }}
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
