name: cd-responders-portal

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to build"
        required: true
        default: "master"

  push:
    paths:
      - "responders/**"

jobs:
  build-api:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: responders/src/API
      BUILD_CONTEXT: "shared=./shared/src"
      IMAGE_FILE: responders/src/API/Dockerfile
      IMAGE_NAME: responders-portal-api
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }} #only exists when the workflow is triggered by workflow_dispatch. It is empty or null when the workflow is triggered by a push.
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build-ui:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: responders/src/UI
      IMAGE_FILE: responders/src/UI/Dockerfile
      IMAGE_NAME: responders-portal-ui
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }} #only exists when the workflow is triggered by workflow_dispatch. It is empty or null when the workflow is triggered by a push.
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
