name: CD Suppliers-portal

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to build"
        required: true
        default: "master"

  push:
    branches:
      - master
    paths:
      - "suppliers/**"

jobs:
  get-pr-number:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.find_pr.outputs.pr_number }}
    # Only run on push events AND only if it's a merge commit (PR merge)
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find PR number from commit message
        id: find_pr
        run: |
          PR_NUMBER=$(echo "${{ github.event.head_commit.message }}" | sed -n 's/.*#\([0-9]\+\).*/\1/p')
          echo "Found PR Number: $PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

  build-api:
    needs: get-pr-number
    if: always()
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: suppliers/src/API
      IMAGE_FILE: suppliers/src/API/Dockerfile
      IMAGE_NAME: suppliers-portal-api
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
      # Use the reliable output from our new job
      PR_NUMBER: ${{ needs.get-pr-number.outputs.pr_number }}
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build-ui:
    needs: get-pr-number
    if: always()
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build-template.yml
    with:
      IMAGE_CONTEXT: suppliers/src/UI
      IMAGE_FILE: suppliers/src/UI/Dockerfile
      IMAGE_NAME: suppliers-portal-ui
      REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      BRANCH: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
      # Use the reliable output from our new job
      PR_NUMBER: ${{ needs.get-pr-number.outputs.pr_number }}
    secrets:
      REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
